import { Variants } from "framer-motion";
import { type Trip} from "@/types/shop/types";

export interface PlanetType {
 
    id: number;
    type: string;
    name: string;
    image: string;
    description: string;
    activities: string[];
    variants?: Variants;
  
}

export const planets : PlanetType[] = [{
    id: 1,
    name: "Mars",
    type: "Basic",
    image: "/planets/mars.webp",
    description: "The red planet is a dusty, cold, desert world with a very thin atmosphere.",
    activities: ["Exploration Canyon", "Base Alpha Dome"],
},
{
    id: 2,
    type:"Premium",
    name: "Jupiter",
    image: "/planets/jupiter.webp",
    description: "The largest planet in our solar system, Jupiter is a gas giant.",
    activities: ["Space Outpost","Moon Cruises"],
},
{
    id: 3,
    name: "Saturn",
    type: "Exclusive",
    image: "/planets/saturn.webp",
    description: "Saturn is the sixth planet from the Sun and the second largest in the Solar System.",
    activities: ["Space Outpost","Moon Cruises"],
},
{
    id: 4,
    name: "Mercury",
    type: "Premium",
    image: "/planets/mercury.webp",
    description: "The closest world to our Sun. A land of extreme contrasts, where you can watch the sunrise twice in one day.",
    activities: ["Solar Flare Observation", "Magma Trekking"],
  },
  {
    id: 5,
    name: "Venus",
    type: "Luxury",
    image: "/planets/venus.webp",
    description: "Hidden beneath thick golden clouds, our sister planet offers high-altitude floating resorts.",
    activities: ["Cloud-City Dining", "Sulfuric Sunset Photography"],
  },
  {
    id: 6,
    name: "Uranus",
    type: "Premium",
    image: "/planets/uranus.webp",
    description: "The tilted ice giant. A cyan-hued world where diamonds may rain from the sky.",
    activities: ["Deep-Core Sound Harvesting", "Vertical Ring-Gliding"],
  },
  {
    id: 7,
    name: "Neptune",
    type: "Exclusive",
    image: "/planets/neptune.webp",
    description: "The furthest sentinel of our system. A deep cobalt sphere whipped by the fastest winds in the galaxy.",
    activities: ["Supersonic Wind-Surfing", "Triton Cryo-Geyser Tours"],
  },
  {
    id: 8,
    name: "Moon",
    type: "Basic",
    image: "/planets/moon.webp",
    description: "Our closest celestial neighbor. Walk where legends first left their footprints and experience the breathtaking of the Moon.",
    activities: ["Low-Gravity Lunar Hikes", "Apollo Site Pilgrimages"],
}

]



export const TRIPS: Trip[] = [
  {
    id: "lunar-alpha",
    name: "Lunar Base Alpha",
    destination: "Moon",
    zone: "inner",
    duration: "3 days",
    departure: "Jun 2027",
    seats: 12,
    risk: "LOW",
    price: 1_200,
    description: "The classic gateway mission. Land on Mare Tranquillitatis and spend two nights in our pressurized habitat.",
    highlights: ["Moonwalk EVA", "Earth-rise viewing", "Crater rover tour"],
    visual: "/planets/moon.webp",
    accent: "#a8b8e8",
  },
  {
    id: "mercury-core",
    name: "Hermes Core Outpost",
    destination: "Mercury",
    zone: "inner",
    duration: "6 days",
    departure: "Aug 2027",
    seats: 4,
    risk: "HIGH",
    price: 8_500,
    description: "An extreme journey to the closest rock to the Sun. Protected by advanced magnetic shielding fields.",
    highlights: ["Solar flare watch", "Caloris Basin trek", "Heavy-gravity shift"],
    visual: "/planets/mercury.webp",
    accent: "#ff8c42",
  },
  {
    id: "venus-clouds",
    name: "Aphrodite Cloud Station",
    destination: "Venus",
    zone: "inner",
    duration: "5 days",
    departure: "Oct 2027",
    seats: 8,
    risk: "HIGH",
    price: 6_900,
    description: "Float among the acid clouds of Venus inside a luxury aerostat colony, high above the crushing surface.",
    highlights: ["Sulfuric sunset view", "Atmospheric diving", "Premium spa lounge"],
    visual: "/planets/venus.webp",
    accent: "#e29578",
  },
  {
    id: "mars-olympus",
    name: "Olympus Mons Expedition",
    destination: "Mars",
    zone: "inner",
    duration: "14 days",
    departure: "Sep 2027",
    seats: 3,
    risk: "MEDIUM",
    price: 3_400,
    description: "The ultimate red planet experience. Hike the base of the largest volcano known in the solar system.",
    highlights: ["Red desert rovering", "Canyon drone racing", "Martian ice harvest"],
    visual: "/planets/mars.webp",
    accent: "#fc4a1a",
  },
  {
    id: "jupiter-storm",
    name: "Io Orbital Overlook",
    destination: "Jupiter",
    zone: "outer",
    duration: "21 days",
    departure: "Jan 2028",
    seats: 6,
    risk: "MEDIUM",
    price: 12_500,
    description: "Cruise around the gas giant and witness the ancient fury of the Great Red Spot from a safe orbital distance.",
    highlights: ["Gas storm hyper-lapse", "Io volcanic eruption", "Europa ice-radar scan"],
    visual: "/planets/jupiter.webp",
    accent: "#f7b731",
  },
  {
    id: "saturn-rings",
    name: "Titan Ring-Rider Resort",
    destination: "Saturn",
    zone: "outer",
    duration: "25 days",
    departure: "Mar 2028",
    seats: 2,
    risk: "LOW",
    price: 15_800,
    description: "The jewel of space tourism. Fly inside Saturn's icy rings and land on the hydrocarbon lakes of Titan.",
    highlights: ["Ice-particle sailing", "Titan low-g skydiving", "Cassini memorial tour"],
    visual: "/planets/saturn.webp",
    accent: "#4b7bec",
  },
  {
    id: "uranus-aurora",
    name: "Titania Deep Station",
    destination: "Uranus",
    zone: "outer",
    duration: "32 days",
    departure: "May 2028",
    seats: 5,
    risk: "MEDIUM",
    price: 19_000,
    description: "An off-grid cruise to the tilted ice giant. Watch the unique vertical ring system and pale blue glow.",
    highlights: ["Vertical ring cruise", "Diamond rain simulation", "Extreme cold-shielding"],
    visual: "/planets/uranus.webp",
    accent: "#20bf6b",
  },
  {
    id: "neptune-abyss",
    name: "Triton Cryo-Port",
    destination: "Neptune",
    zone: "outer",
    duration: "40 days",
    departure: "Nov 2028",
    seats: 4,
    risk: "HIGH",
    price: 24_000,
    description: "Venture to the windswept edge of the outer planets. Witness supersonic storms and cryovolcanoes on Triton.",
    highlights: ["Supersonic wind flyby", "Cryo-geyser climbing", "Dark Spot telemetry"],
    visual: "/planets/neptune.webp",
    accent: "#3867d6",
  },
  // ── EXTRA DEEP SPACE PIANETI ───────────────────────────────────────────────
  {
    id: "pluto-frontier",
    name: "Tombaugh Heart Outpost",
    destination: "Pluto",
    zone: "deep",
    duration: "60 days",
    departure: "Jul 2029",
    seats: 2,
    risk: "EXTREME",
    price: 35_000,
    description: "For true frontier scouts. Stand on the frozen nitrogen heart of Pluto and gaze at the distant, tiny Sun.",
    highlights: ["Charon eclipse watch", "Nitrogen ice skating", "Deep space radio silence"],
    visual: "/planets/pluto.webp", 
    accent: "#a55eea",
  },
  {
    id: "eris-void",
    name: "Dysnomia Void Anchor",
    destination: "Eris",
    zone: "deep",
    duration: "90 days",
    departure: "Dec 2029",
    seats: 1,
    risk: "EXTREME",
    price: 52_000,
    description: "The absolute edge of our chart. A solitary corporate scientific anchor floating in the pitch-black Kuiper void.",
    highlights: ["Interstellar horizon view", "Void-radiation mapping", "Extreme isolation badge"],
    visual: "/planets/eris.webp", 
    accent: "#778ca3",
  },
];

